name: CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Add All Required NuGet Feeds
        run: |
          dotnet nuget add source https://nuget.bepinex.dev/v3/index.json -n BepInEx || true
          dotnet nuget add source https://nuget.reactor.gg/v3/index.json -n Reactor || true
          dotnet nuget add source https://nuget.il2cpp.dev/v3/index.json -n Il2Cpp || true

      - name: Restore Project Dependencies
        run: dotnet restore Reactor/Reactor.csproj --disable-parallel

      - name: Build Reactor Core
        run: dotnet build Reactor/Reactor.csproj -c Release --no-restore -p:CheckEolTargetFramework=false || dotnet build Reactor/Reactor.csproj -c Release -p:CheckEolTargetFramework=false

      - name: Upload Mod DLL
        uses: actions/upload-artifact@v4
        with:
          name: ImpostorReporterMod
          path: "**/bin/Release/**/*.dll"
