name: CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Add BepInEx & Reactor NuGet Feeds
        run: |
          dotnet nuget add source https://nuget.bepinex.dev/v3/index.json -n BepInEx || true
          dotnet nuget add source https://nuget.reactor.gg/v3/index.json -n Reactor || true

      - name: Find and Restore Example Project
        run: |
          PROJ_FILE=$(find . -name "Reactor.Example.csproj" | head -n 1)
          echo "Found project at: $PROJ_FILE"
          dotnet restore "$PROJ_FILE"

      - name: Find and Build Example Project
        run: |
          PROJ_FILE=$(find . -name "Reactor.Example.csproj" | head -n 1)
          dotnet build "$PROJ_FILE" -c Release --no-restore

      - uses: actions/upload-artifact@v4
        with:
          name: ImpostorReporterMod
          path: "**/bin/Release/net6.0/"
